// PEAK PCAN-View trace (.trc). Written as version 2.1, which carries a bus
// column; read as 1.0, 1.1, 1.3 and 2.x.
//
//   ;$FILEVERSION=2.1
//   ;$STARTTIME=46291.3958347222
//   ;$COLUMNS=N,O,T,B,I,d,R,L,D
//         1         0.123 DT  1     0123 Rx -  8    00 11 22 33 44 55 66 77
import 'dart:convert';
import 'dart:typed_data';

import '../can.dart';
import 'log.dart';

/// TRC's STARTTIME: fractional days since 1899-12-30, local time (OLE date).
final _ole = DateTime(1899, 12, 30);

double oleDate(DateTime t) =>
    t.difference(_ole).inMicroseconds / Duration.microsecondsPerDay;

DateTime fromOleDate(double days) =>
    _ole.add(Duration(microseconds: (days * Duration.microsecondsPerDay).round()));

class TrcWriter extends LogWriter {
  var _n = 0;

  TrcWriter(super.sink, super.start) {
    _line(r';$FILEVERSION=2.1');
    _line(';\$STARTTIME=${oleDate(start).toStringAsFixed(10)}');
    _line(r';$COLUMNS=N,O,T,B,I,d,R,L,D');
    _line(';');
    _line(';   Start time: ${start.toIso8601String()}');
    _line(';   Generated by Pantrace');
    _line(';-------------------------------------------------------------------------------');
    _line(';   Message   Time    Type    ID     Rx/Tx');
    _line(';   Number    Offset  |  Bus  [hex]  |  Reserved');
    _line(';   |         [ms]    |  |    |      |  |  Data Length Code');
    _line(';   |         |       |  |    |      |  |  |    Data [hex] ...');
    _line(';   |         |       |  |    |      |  |  |    |');
    _line(';---+-- ------+------ +- +- --+----- +- +- +--- +- -- -- -- -- -- -- --');
  }

  void _line(String s) => sink.add(utf8.encode('$s\r\n'));

  @override
  void writeFrame(CanFrame f) {
    _n++;
    final ms = (micros(f) / 1000).toStringAsFixed(3).padLeft(13);
    final type = f.isError
        ? 'ER'
        : f.fd
            ? (f.brs ? (f.esi ? 'BI' : 'FB') : (f.esi ? 'FE' : 'FD'))
            : f.rtr
                ? 'RR'
                : 'DT';
    final id = f.isError
        ? '-'
        : f.id.toRadixString(16).toUpperCase().padLeft(f.extended ? 8 : 4, '0');
    final dir = f.direction == FrameDirection.tx ? 'Tx' : 'Rx';
    final dlc = f.isError ? 0 : f.fd ? lengthToDlc(f.data.length) : f.data.length;
    // The DLC code implies the length, so FD payloads go out padded to it.
    final data = f.isError || f.rtr
        ? ''
        : f.fd
            ? CanFrame(id: 0, data: Uint8List(fdPaddedLength(f.data.length))..setAll(0, f.data)).dataHex
            : f.dataHex;
    _line('${'$_n'.padLeft(7)} $ms $type ${'${f.channel + 1}'.padLeft(2)} '
            '${id.padLeft(8)} $dir -  ${'$dlc'.padRight(4)} $data'
        .trimRight());
  }
}

const _defaultColumns = {
  '2.0': 'N,O,T,I,d,l,D',
  '2.1': 'N,O,T,B,I,d,R,L,D',
};

DecodedLog readTrc(Uint8List bytes) {
  final lines = const LineSplitter().convert(latin1.decode(bytes));
  var version = '1.1';
  var start = DateTime.fromMillisecondsSinceEpoch(0);
  List<String>? columns;
  final frames = <CanFrame>[];
  var skipped = 0;

  for (final line in lines) {
    if (line.startsWith(';')) {
      final kv = RegExp(r'^;\$(\w+)=(.*)$').firstMatch(line.trim());
      if (kv == null) continue;
      final value = kv.group(2)!.trim();
      switch (kv.group(1)!.toUpperCase()) {
        case 'FILEVERSION':
          version = value;
        case 'STARTTIME':
          final d = double.tryParse(value);
          if (d != null) start = fromOleDate(d);
        case 'COLUMNS':
          columns = value.split(',').map((c) => c.trim()).toList();
      }
      continue;
    }
    final tokens = line.trim().split(RegExp(r'\s+'));
    if (tokens.length < 3) continue;
    final f = version.startsWith('2')
        ? _v2(tokens, columns ?? (_defaultColumns[version] ?? _defaultColumns['2.1']!).split(','), start)
        : _v1(tokens, start);
    if (f == null) {
      skipped++;
    } else {
      frames.add(f);
    }
  }
  return DecodedLog(frames, skipped);
}

Uint8List? _hexBytes(List<String> t, int n) {
  if (t.length < n) return null;
  final out = Uint8List(n);
  for (var i = 0; i < n; i++) {
    final v = int.tryParse(t[i], radix: 16);
    if (v == null || v > 0xFF) return null;
    out[i] = v;
  }
  return out;
}

/// 1.x: `N) offset [Rx|Tx|Warng|Error] id dlc data...` — 1.0 has no direction.
CanFrame? _v1(List<String> t, DateTime start) {
  if (!t[0].endsWith(')')) return null;
  final ms = double.tryParse(t[1]);
  if (ms == null) return null;
  final time = start.add(Duration(microseconds: (ms * 1000).round()));
  var i = 2;
  var dir = FrameDirection.rx;
  if (t[i] == 'Rx' || t[i] == 'Tx') {
    dir = t[i] == 'Tx' ? FrameDirection.tx : FrameDirection.rx;
    i++;
  } else if (t[i] == 'Error' || t[i] == 'Warng') {
    return CanFrame.error('error frame', timestamp: time);
  }
  if (t.length < i + 2) return null;
  final id = int.tryParse(t[i], radix: 16);
  final dlc = int.tryParse(t[i + 1]);
  if (id == null || dlc == null || dlc > 8) return null;
  final rest = t.sublist(i + 2);
  final rtr = rest.isNotEmpty && rest.first == 'RTR';
  final data = rtr ? Uint8List(0) : _hexBytes(rest, dlc);
  if (data == null) return null;
  return CanFrame(
      id: id, extended: t[i].length > 4, rtr: rtr, data: data,
      timestamp: time, direction: dir);
}

/// 2.x: columns named by `$COLUMNS`. Data is everything after the length.
CanFrame? _v2(List<String> t, List<String> cols, DateTime start) {
  final at = <String, String>{};
  for (var i = 0; i < cols.length - 1 && i < t.length; i++) {
    at[cols[i]] = t[i];
  }
  final dataFrom = cols.length - 1; // D is always last
  final ms = double.tryParse(at['O'] ?? '');
  if (ms == null) return null;
  final time = start.add(Duration(microseconds: (ms * 1000).round()));
  final ch = (int.tryParse(at['B'] ?? '1') ?? 1) - 1;
  final type = at['T'] ?? 'DT';
  if (type == 'ER') return CanFrame.error('error frame', timestamp: time, channel: ch);
  // FD without / with bit rate switch, with ESI, with both.
  const fdTypes = {'FD': (false, false), 'FB': (true, false), 'FE': (false, true), 'BI': (true, true)};
  final fdType = fdTypes[type];
  if (type != 'DT' && type != 'RR' && fdType == null) return null; // status, events
  final fd = fdType != null;
  final idText = at['I'] ?? '';
  final id = int.tryParse(idText, radix: 16);
  // L is the DLC code, l (version 2.0) the byte count.
  final dlc = int.tryParse(at['L'] ?? '');
  final len = at['l'] != null ? int.tryParse(at['l']!) : (dlc == null ? null : dlcToLength(dlc, fd: fd));
  if (id == null || len == null || len > (fd ? 64 : 8)) return null;
  final rtr = type == 'RR';
  final data = rtr ? Uint8List(0) : _hexBytes(t.sublist(dataFrom.clamp(0, t.length)), len);
  if (data == null) return null;
  return CanFrame(
    id: id,
    extended: idText.length > 4,
    rtr: rtr,
    fd: fd,
    brs: fdType?.$1 ?? false,
    esi: fdType?.$2 ?? false,
    data: data,
    timestamp: time,
    direction: at['d'] == 'Tx' ? FrameDirection.tx : FrameDirection.rx,
    channel: ch,
  );
}
